### ISSUE TITLE
Pin code validation

### ISSUE THREAD

**Issue by esron** [esron/systranca-server#7]
A request to activate a device, such as opening a door, should receive the user pin code as a form of security manner. If the request pin code does not match the user pin code the response should be a 403 HTTP response.

**Comment by viniciusarre** [comment]
How would this pin code be like? Alphanumerical? Should it be readable by the user or just an overall Token validator would work (something like [JWT](https://www.jsonwebtoken.io/))? Can it be generated by an external library (such as [nanoId](https://github.com/ai/nanoid) ?)

**Comment by esron** [comment]
Hi @viniciusarre .

I was thinking abou a numerical, 4 to 6 length string. Something ease to remember but hard to guest. Just like the pin code in some banks apps.

There's already a route `/door` that accepts a POST request with a user id and a pin code in the body.

And of course, I'm accepting suggestions on how to make things more secure and enhance the user experience.

If you want to take a look in the App client you can find it [here](https://github.com/esron/systranca_app)

**Comment by Vectormike** [comment]
How about user creates pin code manually?

**Comment by viniciusarre** [comment]
I'm not sure... wouldn't it present a possible security threat? I suggest that we create it and register it to db with an expiration date. (I have a mental map on how it would work).  I've been thinking about a simple way of doing this... which would require generating pin code according to the request's [timestamp](https://stackoverflow.com/questions/8012002/create-a-unique-number-with-javascript-time), register it to the user and require somehow the user's `jwt` in order to properly authenticate... but this is still just an idea, I'm still familiarizing myself with the system in general...

**Comment by esron** [comment]
I'll try to be more clear.

The pin code is something that you try to assure that is the actual user that is making a request to activate a device.

Imagine that a user lets their phone unlocked on a table, and another person gets the phone and try to activate some device, the pin code is to protect from this scenario.

I agree that the user must be authenticated via a `jwt` ou a `Oauth` flow. But the pin code is for another purpose.

If there is any misconception when can clear in this thread. Thank's for the help.

**Comment by esron** [comment]
solved in #18
